CREATE USER COMPARE
  IDENTIFIED BY VALUES '0A23CF95627B6AC1'
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO COMPARE;
  GRANT CONNECT TO COMPARE;
  GRANT RESOURCE TO COMPARE;
  GRANT SELECT_CATALOG_ROLE TO COMPARE;
  ALTER USER COMPARE DEFAULT ROLE ALL;

GRANT UNLIMITED TABLESPACE TO COMPARE;
GRANT SELECT ANY DICTIONARY TO COMPARE;
