break on report
compute sum of total free used on report
SELECT T.TABLESPACE_NAME TBLSPC,
       ROUND(T.BYTES/(1024*1024) ) TOTAL,
       ROUND(T.MAXBYTES/(1024*1024) ) MAX,
       ROUND(SUM(F.BYTES)/(1024*1024)) FREE,
       ROUND((SUM(F.BYTES)/T.BYTES * 100)) FREEPCT,
       ROUND(T.BYTES/(1024*1024) ) -ROUND(SUM(F.BYTES)/(1024*1024)) USED,
       ROUND(((T.BYTES-SUM(F.BYTES))/T.BYTES) *100) USEDPCT,
       ROUND(((T.BYTES-SUM(F.BYTES))/T.maxBYTES) *100) usedpct2
FROM SYS.DBA_FREE_SPACE F,
     (SELECT TABLESPACE_NAME, sum(bytes) bytes, SUM(decode(autoextensible,'YES',MAXBYTES,BYTES))   maxBYTES
      FROM SYS.DBA_DATA_FILES
      GROUP BY TABLESPACE_NAME
       UNION 
       SELECT TABLESPACE_NAME, sum(bytes) bytes, SUM(decode(autoextensible,'YES',MAXBYTES,BYTES))   maxBYTES
      FROM SYS.DBA_TEMP_FILES
      GROUP BY  TABLESPACE_NAME ) T
WHERE T.TABLESPACE_NAME=F.TABLESPACE_NAME(+) 
GROUP BY T.TABLESPACE_NAME, T.BYTES,T.MAXBYTES
ORDER BY T.TABLESPACE_NAME; 