 SELECT
  L.GROUP# GROUP_NUMBER,
  LF.MEMBER FILENAME,
  L.STATUS,
  L.ARCHIVED,
  L.BYTES,
  L.FIRST_CHANGE#,
  L.FIRST_TIME
FROM
  V$LOG L,
  V$LOGFILE LF
WHERE
  LF.GROUP#=L.GROUP#
ORDER BY
  L.GROUP#;