SELECT SUBSTR(TBPRK_PK,1,16)      TBPRK_PK,
       SUBSTR(MESSAGE_ID,1,16)    MESSAGE_ID,
       SUBSTR(MESSAGE_TYPE,1,25)  MESSAGE_TYPE,
       TIME_STAMP,
       COMPONENT,
       SOURCE,
       SUBSTR(TARGET,1,18)        TARGET,
       SUBSTR(SUBSCRIBER,1,10)    SUBSCRIBER,
       SUBSTR(DEPENDENCY,1,15)    DEPENDENCY,
       --EVENT_XML,
       SUBSTR(REASON,1,25)        REASON
FROM   TBPRK_PARKING_LOT;
